### ISSUE TITLE
docker-compose.yaml comma-separate validators

### ISSUE THREAD

**Issue by ladidan** [TobiWo/eth-duties#38]
Hi folks,
cool tool!

This is just a quick suggestion for the compose.yaml. I'd argue it is much leaner to comma-separate validator indices here, e.g.

```
        container_name: eth-duties
        restart: on-failure
        command:
        - --validators
        - "1234,12345,123456"
        - --beacon-node
        - http://localhost:5052
```
